variables:   
  baseUrl: "https://go-sb.nimbi.net.br/tecfabricasb"

stages:
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

BlogAgiVictor:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm run start:ci &
    # run Cypress tests
    - npx cypress run --browser chrome --spec cypress/e2e/buscaArtigoValido.cy.js
    - npx cypress run --browser chrome --spec cypress/e2e/buscaPorArtigoInvalido.cy.js
  artifacts:
    when: always
    paths:
      - cypress/videos/**/*.mp4
      - cypress/screenshots/**/*.png
    expire_in: 1 day
